name: Run Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the notebook
      - name: Execute Jupyter Notebook
        run: |
          python -m pip install nbconvert  # Install nbconvert if not already installed
          jupyter nbconvert --to notebook --execute trashClassification_Adamata.ipynb --output executed_notebook.ipynb
