name: Model Development Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "Warning: Skipping incompatible dependencies"


      # Step 4: Train the model
      - name: Train model
        run: |
          python trashclassification_adamata.py

      # Step 5: Publish artifacts (optional)
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: model.h5
